
# ==================================================================================================== #

name: aplicacion
description: Permite consultar las farmacias de guardia de Navarraque estén disponibles los próximos ~10 días.

# ==================================================================================================== #

publish_to: 'none'

# ==================================================================================================== #

version: 1.0.0+1

# ==================================================================================================== #

environment:
  sdk: ">=2.7.0 <3.0.0"

# ==================================================================================================== #

dependencies:
  flutter:
    sdk: flutter
  get:
  get_storage:
  geocoding: ^1.0.5
  flutter_map: ^0.10.1+1
  # google_maps_flutter: 1.0.5
  # location: ^3.0.0
  # intl: ^0.16.1

  cupertino_icons: ^0.1.3

# ==================================================================================================== #

dev_dependencies:
  flutter_test:
    sdk: flutter
  
# ==================================================================================================== #

flutter:
  assets:
    - data/farmaciasDeGuardia.json
  fonts:
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Bold-Italic.ttf
          weight: 700
          style: italic
    - family: RobotoMono
      fonts: 
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular-Italic.ttf
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold-Italic.ttf
          weight: 700
          style: italic
  uses-material-design: true

# ==================================================================================================== #
